### ISSUE TITLE
Any impact if we directly use "labgrid-client -p place lock"?

### ISSUE THREAD

**Issue by daocloud123** [NXP/fc#1]
Hi, there,

I'd like to take a try for this, but one question before I started:

If I directly use `labgrid-client -p place lock` when a place is idle, can I still get the place access?
That way, a conflict there if lava is using a device? Or you suppose the user won't use `labgrid-client -p lock` directly?

**Comment by atline** [comment]
By default, when `FC` starts, it will automatically own all labgrid places' ownership, that means if the end user use `labgrid-client lock`, they will never lock the place successfully, the end user should use `fc-client` to lock the board. This way, no conflict will be seen.
